name: fastapi_app

on: # specify the build to trigger the automated ci/cd
  push:
    branches:
      - "fantasy-leaderboard"

jobs:
  build:
    name: Build Docker image
    runs-on: ubuntu-latest # specify the build machine
    steps:
      - # checkout to the repository on the build machine
        name: Checkout
        uses: actions/checkout@v3
      # - # login to Docker Hub using the secrets provided
      #   name: Login to Docker Hub
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.DOCKER_HUB_NAME }}
      #     password: ${{ secrets.DOCKER_HUB_TOKEN }}
      # - # create a build kit builder instance
      #   name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v2
      # - # build the container image and push it to Docker \
      #   # Hub with the name stash-out-staging.
      #   name: Build and push
      #   uses: docker/build-push-action@v4
      #   with:
      #     context: .
      #     file: ./Dockerfile
      #     push: true
      #     tags: ${{ secrets.DOCKER_HUB_NAME }}/${{ secrets.DOCKER_REPO_NAME }}:latest
      #     build-args: |
      #       ENV=${{ secrets.ENV_FILE }}
      #   # Auto Deployment
      - name: Deploy Docker image to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_HOST_NAME_LEADERBOARD }}
          username: ubuntu
          key: ${{ secrets.AWS_SSH_KEY_PROD }}
          script: |
            sudo docker-compose down
            sudo docker-compose pull
            sudo docker-compose up -d --build
      
